version: '3.8'

services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: react-app
    ports:
      - "5173:5173"
    volumes:
      - /usr/src/app/node_modules
    env_file:
      - .env.local
    environment:
      - NODE_ENV=development
    command: npm run dev -- --host
